### ISSUE TITLE
Guide/advice on customizing for theme for use with Default Dark+ colors for python semantic highlighting?

### ISSUE THREAD

**Issue by Up50qyx** [ykrx/lightbulb#5]
Hello!  First of all, thank you for making this theme!  A rare and refreshing find in the usual endless catalogue of One Dark forks in the vsc marketplace.  I have a question: I am very new to world of theme customization, and I was wondering how to best go about configuring your theme?

For context, I want to use the pylance extension's default semantic syntax highlights for the dark+ color scheme (listed [here](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_plus.json)), specifically with enabling some of the semantic highlighting features, with your existing theme.  I think it will look nice and will personally give me the feel of the editor I am looking for.  Including but not limited to:

- the color of the variables when they are used vs unused
- color of GLOBAL vars vs global_vars vs __dunder__
- color of the self argument in a class definition
- underlining and bolding classnames in a class defition, etc...

I will admit, I am an extreme noob when it comes to editing vs code themes, but I have not been able to find a concise guide anywhere.  I was wondering if you could help me out, or point to the direction of where I should look?

Or, in the event that semantic highlighting for python is not yet supported, are you open to accepting contributions/PRs?  Thank you!

**Comment by ykray** [comment]
Thank you! Glad you like it! If I'm understanding correctly, you're trying to modify language-specific token colors. You can do so by editing the `editor.tokenColorCustomizations.textMateRules` array in your `settings.json`. 

To find token scope names: 
> Command Palette > **Inspect Editor Tokens and Scopes**

## Example for `self` in Python class definitions:

1. Determine scope(s) via **"Inspect Editor Tokens and Scopes"**
<img width="657" alt="image" src="https://github.com/ykray/lightbulb/assets/43590347/ff256476-9fa1-4a01-8b7b-905d570ca3f2">

2. Add/modify TextMate rule for said scope(s):

```jsonc
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["variable.language.special.self.python"],
        "settings": {
          "foreground": "#FF0000",
          "fontStyle": "bold"
        }
      },
      // ...
    ]
}
```
Result:

<img width="200" alt="image" src="https://github.com/ykray/lightbulb/assets/43590347/494ced8b-cb49-463e-94b0-4e0c4db3e183">

**Comment by ykray** [comment]
As for general customization, you can override Lightbulb's colors via `workbench.colorCustomizations` as follows:

```jsonc
"workbench.colorCustomizations": {
    "[Lightbulb]": {
      "activityBar.activeBackground": "#FF0000",
      // ...
    }
}
```

**Comment by Up50qyx** [comment]
Got it, I will add those to my global user settings.json.  But what is the difference between the colors specified in workbench.colorCustomizations and editor.tokenColorCustomization and editor.semanticTokenColorCustomization?  Is there like a precedence order between the three?

**Comment by ykray** [comment]
Wasn't even aware about VSCode's semantic highlighting option myself, just updated Lightbulb to support it.

**Comment by ykray** [comment]
But in regards to your question,

### `workbench.colorCustomizations`
> Customize colors of VSCode's UI elements (as well as UIs of extensions that support it)

### `editor.tokenColorCustomization`
> Customize colors of tokens based on TextMate scopes

### `editor.semanticTokenColorCustomization`
> Customize colors of tokens based on semantic highlighting, overriding TextMate scopes

**Comment by Up50qyx** [comment]
Perfect, thank you!  will try these out soon -> thank you again
