### ISSUE TITLE
colors in new coverage API are off

### ISSUE THREAD

**Issue by KingOfTac** [ykrx/lightbulb#6]
The foreground colors for the inline test coverage symbols in vscode's new coverage API use their default value while their backgrounds use the gold color from Lightbulb's palette. This leads to poor contrast.

~~I'm not entirely sure which theme tokens to use for this yet.~~
edit: It appears to be `testing.coverCountBadgeForeground`, though it doesn't seem to actually change anything. It could be a bug.

<img width="207" alt="Screenshot 2024-05-07 at 9 08 53 PM" src="https://github.com/ykrx/lightbulb/assets/32497422/e4ef2a06-710c-4eff-86d1-c9457324c52a">

edit: [release notes](https://code.visualstudio.com/updates/v1_88#_test-coverage) for the coverage API

**Comment by ykrx** [comment]
Updated the background color of the badges, tho foreground color seems to be broken on VS Code's side for now 🙃

<img width="126" alt="image" src="https://github.com/ykrx/lightbulb/assets/43590347/62fb2a52-5de5-477e-9542-1f0307d80f85">

**Comment by KingOfTac** [comment]
> Updated the background color of the badges, tho foreground color seems to be broken on VS Code's side for now

Appreciate the quick resolution. I created an issue over at vscode to track the color token

**Comment by ykrx** [comment]
> Appreciate the quick resolution. I created an issue over at vscode to track the color token

Nice, wouldn't be the first time color customization wasn't fully-fleshed out with new interface features. I randomly discover similar ones from time to time and [sometimes fix them](https://github.com/microsoft/vscode/pull/189282) when they're annoying enough lol

**Comment by KingOfTac** [comment]
@ykrx Looks like vscode has fixed this and released it.
